package presenter;

public enum EVENTS {
    C_LOAD_FILE_USER,
    C_LOAD_FILE_SALES,
    C_SHOW_PERCENTAGE_TABLE,
    C_SHOW_TABLE_SALES_BY_DATE,
    C_SHOW_GENERAL_SALES,
    C_SHOW_TABLE_USER_NUMSALE,
    C_EXPORT_FILES

}
